# Configuration for probot-auto-merge   - https://github.com/bobvanderlinden/probot-auto-merge

deleteBranchAfterMerge: true
reportStatus: true

mergeMethod: squash

blockingLabels:
- dont-merge

minApprovals:
  COLLABORATOR: 2

requiredLabels:
- qa-approve
